<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["partner", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create partner
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "partner/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNip" class="col-sm-2 control-label">NIP</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["NIP", "type" => "number", "class" => "form-control", "id" => "fieldNip"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldWebiste" class="col-sm-2 control-label">Webiste</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["webiste", "size" => 30, "class" => "form-control", "id" => "fieldWebiste"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDate" class="col-sm-2 control-label">DATE</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["DATE", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
