<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["product", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit product
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "product/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPartnerId" class="col-sm-2 control-label">Partner</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["partner_id", "type" => "number", "class" => "form-control", "id" => "fieldPartnerId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCurrency" class="col-sm-2 control-label">Currency</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["currency", "size" => 30, "class" => "form-control", "id" => "fieldCurrency"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAvailability" class="col-sm-2 control-label">Availability</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["availability", "type" => "number", "class" => "form-control", "id" => "fieldAvailability"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDate" class="col-sm-2 control-label">Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
